<?php $admin_title = 'Kelola Menu'; ?>
<div class="row g-4">
  <div class="col-lg-4"><div class="dc-admin-card"><h4>Tambah / Edit Menu</h4><form method="POST" action="<?= url('admin/menu/save') ?>" enctype="multipart/form-data"><?= csrf_field() ?><input type="hidden" name="id" id="menuId"><input type="hidden" name="foto_lama" id="menuFotoRaw">
    <label class="dc-form-label">Nama Menu</label><input name="nama" id="menuNama" class="form-control dc-input mb-2" required>
    <label class="dc-form-label">Kategori</label><select name="kategori" id="menuKategori" class="form-select dc-input mb-2"><option>Makanan</option><option>Minuman</option><option>Dessert</option></select>
    <label class="dc-form-label">Harga</label><input type="number" name="harga" id="menuHarga" class="form-control dc-input mb-2" required>
    <div class="row g-2"><div class="col-6"><label class="dc-form-label">Stok</label><input type="number" name="stok" id="menuStok" class="form-control dc-input mb-2" required></div><div class="col-6"><label class="dc-form-label">Minimum</label><input type="number" name="minimum_stok" id="menuMinStok" class="form-control dc-input mb-2" value="5" required></div></div>
    <label class="dc-form-label">Upload Foto Menu</label><input type="file" name="foto_upload" class="form-control dc-input mb-2" accept="image/*"><small class="text-muted d-block mb-2">JPG, PNG, WEBP maksimal 2 MB. Boleh kosong jika memakai URL.</small>
    <label class="dc-form-label">URL Foto <span class="text-muted fw-normal">(opsional)</span></label><input name="foto_url" id="menuFoto" class="form-control dc-input mb-2" placeholder="https://...">
    <label class="dc-form-label">Deskripsi</label><textarea name="deskripsi" id="menuDeskripsi" rows="3" class="form-control dc-input mb-2"></textarea>
    <label class="form-check mb-3"><input type="checkbox" name="unggulan" id="menuUnggulan" class="form-check-input"> Menu unggulan landing page</label><button class="btn dc-btn-submit w-100">Simpan Menu</button>
  </form></div></div>
  <div class="col-lg-8"><div class="dc-admin-card"><h4>Daftar Menu</h4><div class="table-responsive"><table class="table dc-table align-middle"><thead><tr><th>Menu</th><th>Kategori</th><th>Harga</th><th>Stok</th><th>Min.</th><th>Unggulan</th><th>Aksi</th></tr></thead><tbody><?php foreach ($menus as $m): ?><tr><td><div class="dc-admin-menu-cell"><img src="<?= e($m['foto']) ?>" alt=""><span><?= e($m['nama']) ?></span></div></td><td><?= e($m['kategori']) ?></td><td><?= rupiah($m['harga']) ?></td><td><?= e($m['stok']) ?></td><td><?= e(isset($m['minimum_stok']) ? $m['minimum_stok'] : 5) ?></td><td><?= !empty($m['unggulan']) ? '<span class="dc-status verified">Ya</span>' : '<span class="text-muted">Tidak</span>' ?></td><td><button class="btn btn-sm btn-outline-dark menu-edit" data-menu='<?= e(json_encode($m)) ?>'>Edit</button><form method="POST" action="<?= url('admin/menu/delete') ?>" class="d-inline" onsubmit="return confirm('Hapus menu ini?')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($m['id']) ?>"><button class="btn btn-sm btn-outline-danger">Hapus</button></form></td></tr><?php endforeach; ?></tbody></table></div></div></div>
</div>
